package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.25

import (
	"context"
	"go-gql-sample/app/internal/dataloader"
	"go-gql-sample/app/internal/infrastructure/server/graph"
	"go-gql-sample/app/internal/infrastructure/server/graph/model"
	"log"
	"strconv"
)

// User is the resolver for the user field.
func (r *todoResolver) User(ctx context.Context, obj *model.Todo) (*model.User, error) {
	log.Print("@@@@@@@@@@@@@@")
	log.Print(obj)
	res, err := dataloader.LoadUser(ctx, obj.UserID)
	if err != nil {
		return nil, err
	}

	var usersModel []*model.User
	for _, user := range res {
		usersModel = append(usersModel, &model.User{
			ID:   strconv.Itoa(user.ID),
			Name: user.Name,
		})
	}
	return usersModel[0], err
}

// Todo returns graph.TodoResolver implementation.
func (r *Resolver) Todo() graph.TodoResolver { return &todoResolver{r} }

type todoResolver struct{ *Resolver }
