// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Todo struct {
	ent.Schema
}

func (Todo) Fields() []ent.Field {
	return []ent.Field{field.Int("id").SchemaType(map[string]string{"postgres": "bigserial"}), field.String("todo"), field.Int("user_id").Optional(), field.Int("todo_statuses_id").Optional(), field.Time("created_at"), field.Time("updated_at")}
}
func (Todo) Edges() []ent.Edge {
	return []ent.Edge{edge.From("todo_statu", TodoStatus.Type).Ref("todos").Unique().Field("todo_statuses_id"), edge.From("user", User.Type).Ref("todos").Unique().Field("user_id")}
}
func (Todo) Annotations() []schema.Annotation {
	return nil
}
