// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type TodoStatus struct {
	ent.Schema
}

func (TodoStatus) Fields() []ent.Field {
	return []ent.Field{field.Int("id").SchemaType(map[string]string{"postgres": "bigserial"}), field.String("status"), field.Time("created_at"), field.Time("updated_at")}
}
func (TodoStatus) Edges() []ent.Edge {
	return []ent.Edge{edge.To("todos", Todo.Type)}
}
func (TodoStatus) Annotations() []schema.Annotation {
	return nil
}
