// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-gql-sample/app/ent/arinternalmetadatum"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ArInternalMetadatum is the model entity for the ArInternalMetadatum schema.
type ArInternalMetadatum struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Value holds the value of the "value" field.
	Value string `json:"value,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ArInternalMetadatum) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case arinternalmetadatum.FieldID, arinternalmetadatum.FieldValue:
			values[i] = new(sql.NullString)
		case arinternalmetadatum.FieldCreatedAt, arinternalmetadatum.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type ArInternalMetadatum", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ArInternalMetadatum fields.
func (aim *ArInternalMetadatum) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case arinternalmetadatum.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				aim.ID = value.String
			}
		case arinternalmetadatum.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				aim.Value = value.String
			}
		case arinternalmetadatum.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				aim.CreatedAt = value.Time
			}
		case arinternalmetadatum.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				aim.UpdatedAt = value.Time
			}
		}
	}
	return nil
}

// Update returns a builder for updating this ArInternalMetadatum.
// Note that you need to call ArInternalMetadatum.Unwrap() before calling this method if this ArInternalMetadatum
// was returned from a transaction, and the transaction was committed or rolled back.
func (aim *ArInternalMetadatum) Update() *ArInternalMetadatumUpdateOne {
	return NewArInternalMetadatumClient(aim.config).UpdateOne(aim)
}

// Unwrap unwraps the ArInternalMetadatum entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (aim *ArInternalMetadatum) Unwrap() *ArInternalMetadatum {
	_tx, ok := aim.config.driver.(*txDriver)
	if !ok {
		panic("ent: ArInternalMetadatum is not a transactional entity")
	}
	aim.config.driver = _tx.drv
	return aim
}

// String implements the fmt.Stringer.
func (aim *ArInternalMetadatum) String() string {
	var builder strings.Builder
	builder.WriteString("ArInternalMetadatum(")
	builder.WriteString(fmt.Sprintf("id=%v, ", aim.ID))
	builder.WriteString("value=")
	builder.WriteString(aim.Value)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(aim.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(aim.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ArInternalMetadata is a parsable slice of ArInternalMetadatum.
type ArInternalMetadata []*ArInternalMetadatum
