// Code generated by ent, DO NOT EDIT.

package todo

const (
	// Label holds the string label denoting the todo type in the database.
	Label = "todo"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTodo holds the string denoting the todo field in the database.
	FieldTodo = "todo"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldTodoStatusesID holds the string denoting the todo_statuses_id field in the database.
	FieldTodoStatusesID = "todo_statuses_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTodoStatu holds the string denoting the todo_statu edge name in mutations.
	EdgeTodoStatu = "todo_statu"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the todo in the database.
	Table = "todos"
	// TodoStatuTable is the table that holds the todo_statu relation/edge.
	TodoStatuTable = "todos"
	// TodoStatuInverseTable is the table name for the TodoStatus entity.
	// It exists in this package in order to avoid circular dependency with the "todostatus" package.
	TodoStatuInverseTable = "todo_status"
	// TodoStatuColumn is the table column denoting the todo_statu relation/edge.
	TodoStatuColumn = "todo_statuses_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "todos"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for todo fields.
var Columns = []string{
	FieldID,
	FieldTodo,
	FieldUserID,
	FieldTodoStatusesID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
